# Generated by Django 2.0.4 on 2018-04-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_topic_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='order',
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
