# Generated by Django 2.0.4 on 2018-04-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
